Fixed due to esp32 package 3.0.1 update
rt-net/pico_micro_ros_arduino_examples pull request #20
Opened 2024-06-06 08:14 UTC by aoki-rt

# What does this implement/fix?

ESP32 package 3.0.1にアップデートに合わせた修正

# Does this close any currently open issues?

ありません

# How has this been tested?

実機で動作確認をしました

# Any other comments?

ブランチ名が3.0.0になっていますが、実際のesp32 packageは3.0.1を使っています。

# Checklists

- [x]  I have read the CONTRIBUTING guidelines.
    
    - If there is no guideline in the repository, [rt-net organization's guideline](https://github.com/rt-net/.github/blob/master/CONTRIBUTING.md) applies.
- [x]  I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same change.

2024-06-18 07:22 UTC, ShotaAk requested changes
レビューしました。
コメントの確認お願いします。

また、Lintでエラーが出ているので修正お願いします。

2024-06-18 07:22 UTC, ShotaAk commented on uROS_STEP10_tfMsg/interrupt.ino
> +// Copyright 2024 RT Corporation
Copyrightには発行年を記載します。
このリポジトリはすでにオープンにしているので、発行年の更新は不要です。

他の変更も削除お願いします。

2024-06-18 07:22 UTC, ShotaAk commented on uROS_STEP10_tfMsg/uROS_STEP10_tfMsg.ino
> +  timerStart(g_timer0);
Pi:Co V2 リポジトリと同様に、 //1MHz(1us)　と　//1000 * 1us(1kHz) 表記に変更お願いします。

他のコメントも同様に対応お願いします。

2024-06-19 05:15 UTC, aoki-rt commented on uROS_STEP10_tfMsg/uROS_STEP10_tfMsg.ino
> +  timerStart(g_timer0);
変更しました

2024-06-19 05:15 UTC, aoki-rt commented on uROS_STEP10_tfMsg/interrupt.ino
> +// Copyright 2024 RT Corporation
変更しました

2024-07-04 01:26 UTC, ShotaAk commented
LGTMです

2024-07-04 01:27 UTC, merged